### ISSUE TITLE
image error.

### ISSUE THREAD

**Issue by rwijbenga** [htvekov/openHASP-Sonos-media-player#1]
Hi,
 I get this error on the "openHASP push image to plate" automation:

Error: SwitchPlate.async_push_image() got an unexpected keyword argument 'fitscreen'

Any idea on how to resolve that?

**Comment by htvekov** [comment]
`fitscreen` was added to the Custom Component main branch code with commit b2ed186 (January 30th, 2023)
So you need to update your openHASP Custom Component (latest version is 0.7.1)

Also note that you can't use the latest 'official' openHASP v0.6.3 
At least 0.6.4-dev is required. I would strongly recommend latest rc8 version(future v0.7.x most likely)
The latest rc versions contains a lot of improvements since the early 0.6.4-dev days and has proven very stable.

**openHASP Sonos Prerequisities:
openHASP 0.6.4-dev
commit 7a83367 or newer (January 18th, 2023)
openHASP Custom Component installed in HA
main branch commit b2ed186 or newer required (January 30th, 2023)**

**Comment by rwijbenga** [comment]
In HACS it show version 0.6.6, so I thought that was ok.

Now I have changed it to 0.7.1 beta and it works. :)

**Comment by htvekov** [comment]
Feel free to contact me if you experience other issues with the openHASP Sonos configuration.
Most likely easiest through the openHASP Discord channel (same htvekov handle as here on Github)
